[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
#solc = "0.8.22"
optimizer = true
optimizer_runs = 999999
bytecode_hash = "none"
evm_version = "shanghai"

[invariant]
runs = 20
depth = 5
fail_on_revert = false



[profile.default.fmt]
wrap_comments = true


[profile.test]
via-ir = false

